---
application:
  name: "s-shop-project-backend"
  project: "S-project"
  organization: "QoveryCommunity"
routers:
- name: "main-s-shop-project-backend"
  routes:
  - application_name: "s-shop-project-backend"
    paths:
    - "/*"
