const STATUS_CODES = {
    OK: 200,
    INTERNAL_SERVER_ERROR: 500,
    BAD_REQUEST: 401,
    NOT_FOUND: 400
}
TIMEOUT_RESPONSE = 5000;
module.exports = {
    TIMEOUT_RESPONSE: TIMEOUT_RESPONSE,
    STATUS_CODES: STATUS_CODES
};
